## This content is duplicated here from configs/config_designers.yml because I'm building this site through Github Pages, and Github Pages just looks for the _config.yml file in the root directory to create the build.
# project definitions
project: doc_designers
audience: designers
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Documentation
homepage_title: Documentation for Open-Classifieds and Yclas
site_title: Documentation for Open-Classifieds and Yclas
disqus_shortname: forumopenclassifieds
google_analytics: UA-55615337-3
github_editme_path: kotsios5/documentation-test-theme
# don't use a slash before or after the above path. here's how this url gets written out in page.html: https://github.com/{{site.github_editme_path}}{{page.url | replace: '.html', '.md'}}
# variables

sidebar_tagline: designers
sidebar_version: version 3.0



exclude:
  - doc_writers*
  - configs/
  - _site

# same for all
baseurl: "http://kotsios5.github.io/documentation-test-theme/"
# feedback_email: tomjohnson1492@gmail.com
sidebar_accordion: true
markdown: redcarpet
print: false
theme_file: theme-green.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: pygments

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true